### ISSUE TITLE
Uncaught TypeError: $(...).zIndex is not a function

### ISSUE THREAD

**Issue by rinkudas** [zorab47/jquery.ui.monthpicker#10]
Not able to use in production mode.

(index):348 Uncaught TypeError: $(...).zIndex is not a function
    at HTMLInputElement._showMonthpicker ((index):348)
    at HTMLInputElement.dispatch (jquery-1.9.1.js:3074)
    at HTMLInputElement.elemData.handle (jquery-1.9.1.js:2750)

![sc1](https://cloud.githubusercontent.com/assets/2833621/21765715/9b05c252-d690-11e6-993e-91db0332e9e2.png)

**Comment by kjholla** [comment]
As per the Jquery-ui change log https://jqueryui.com/changelog/1.12.0/, version 1.12.0 has removed support for .zIndex().

Perhaps jquery-ui-monthpicker needs an update to retain compatibility?

**Comment by zorab47** [comment]
Thanks for reporting the issue!

Is there a flexible way of removing it conditionally for new versions while staying consistent for older ones?

**Comment by BrandonNoad** [comment]
👍  I'm running into this as well.

There is an upgrade guide here: https://jqueryui.com/upgrade-guide/1.12/#removed-zindex

**Comment by zorab47** [comment]
Thanks @BrandonNoad. That is probably the best solution until the `appendTo` becomes the only consistently working method.

**Comment by zorab47** [comment]
I released v1.0.2 and published it to npm. The change was to introduce an internal `_zIndex()` function to replace the removed function in jQuery UI.

Re-open the issue if it doesn't fix the issue. Thanks for reporting!
