### ISSUE TITLE
jQuery Version

### ISSUE THREAD

**Issue by kriskd** [zorab47/jquery.ui.monthpicker#8]
What version of jQuery will this plugin work with.  I upgraded from 2.1.4 to 2.2.0 and it appears to no longer work.  Could you please verify?

**Comment by zorab47** [comment]
Great question. I'll double check the compatibility and add it to the documentation.

What exceptions, if any are you seeing?

**Comment by zorab47** [comment]
I can confirm it doesn't work on 2.2.0, but 2.1.4 and earlier do work. Time to dig into what API changes in 2.2.0 are causing the issue. Any ideas?

**Comment by zorab47** [comment]
Removing two `undefined` key press related callbacks fixed the monthpicker for jQuery 2.2.0.

See more detail in commit https://github.com/zorab47/jquery.ui.monthpicker/commit/4ceacbfbe06ea81308d01a67946054673be6aab9.
