### ISSUE TITLE
maxDate and minDate fail if dateFormat is set to "MM, yy"

### ISSUE THREAD

**Issue by TheBigK** [zorab47/jquery.ui.monthpicker#9]
```
$(".resumeExperienceFromYear").monthpicker({
			defaultDate: '-20y',
            yearRange: 'c-60:c',
			changeYear: true,
            changeMonth: true,
            dateFormat: "MM, yy",
			onSelect: function( selected ) {
				$(".resumeExperienceTillYear").monthpicker( "option", "minDate", selected );
			}
		});

		$(".resumeExperienceTillYear").monthpicker({
            defaultDate: '-60y',
			changeYear: true,
            changeMonth: true,
			onSelect: function( selected ) {
				$(".resumeExperienceFromYear").monthpicker( "option", "maxDate", selected );
			}
		});

```

If From date format is set to "MM, yy"; the the Till year starts at 2182. Apparently this is a bug with the library. Also, the default year range is set to minDate + 10 years. Is there any way to change this to  minDate + current year?

Would really appreciate response. Have already spent ~3 days on this.

**Comment by yohancreemers** [comment]
The parameter selected of the onSelect method returns a formatted string ("MM, yy" in your case). The minDate and maxDate options only work with a real JavaScript date, eg new Date(2016, 7 - 1, 1), and with offsets from today. 
So, you will have to convert the formatted date string into a Date object, to set the maxDate option.

**Comment by TheBigK** [comment]
Update: The fix was darn simple. I just had to specify dateFormat: "MM, yy" in the Till Year and the plugin works absolutely fine. http://jsfiddle.net/jakecigar/qqjh09qx/

Now the only issue remaining -

The 'till' date automatically selects range = fromDate + 10 years. Is there any way to improve the range to the current date?

**Comment by zorab47** [comment]
Are you asking about the year range setting? `yearRange: 'c-60:c'`

If so, you could try: `yearRange: 'c-60:c+0'` or `yearRange: 'c-60:c+1'`.

If not, could you provide more information?

**Comment by TheBigK** [comment]
Following setup worked for my specific case - 
`$(".resumeExperienceFromYear").monthpicker({
            defaultDate: '-20y',
            yearRange: 'c-60:c',
            changeYear: true,
            changeMonth: true,
            dateFormat: "MM, yy",
            onSelect: function(selected, inst) {
                console.log(arguments);
                if ($(".resumeExperienceTillYear").val() === "")
                    $(".resumeExperienceTillYear")
                        .monthpicker("setDate", new Date(inst.selectedYear + 5, inst.selectedMonth, 1))
                        .monthpicker("option", "minDate", selected)
            }
        });

        $(".resumeExperienceTillYear").monthpicker({
            defaultDate: '-60y',
            yearRange: 'c-60:c',
            changeYear: true,
            changeMonth: true,
            dateFormat: "MM, yy",
            maxDate: '+0y'
        });`

That said, a typical use case for monthpicker is to use it for 'From' - 'Till' fields. Can you make the monthpicker allow to show 'Current / Ongoing' in the till-field, for any ongoing task / activity / event? I'd love to see this a 'core' functionality. If not, is there any easy way to do this?

**Comment by zorab47** [comment]
No, I don't think it has range selection capabilities. It is basically a modified (older) version of the [jQuery datepicker](https://jqueryui.com/datepicker/) widget. Most of the options supported by datepicker are covered in the monthpicker as well.

**Comment by zorab47** [comment]
Any updates here? If so, please feel free to reopen the issue.
